//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptopiaMT.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdoptopiaMT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _05d20bb5_f64d_4cbe_a607_149bed3d7f7f_16_9_aspect_ratio_default_0_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("05d20bb5-f64d-4cbe-a607-149bed3d7f7f_16-9-aspect-ratio_default_0-removebg-preview" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1653826510_995351_1653826595_noticia_normal_recorte1 {
            get {
                object obj = ResourceManager.GetObject("1653826510_995351_1653826595_noticia_normal_recorte1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _186409_arrow_right_next_icon {
            get {
                object obj = ResourceManager.GetObject("186409_arrow_right_next_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5402405_track_next_ui_media_forward_icon {
            get {
                object obj = ResourceManager.GetObject("5402405_track_next_ui_media_forward_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _554795 {
            get {
                object obj = ResourceManager.GetObject("554795", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _70ac8c63e43ab8d80284b9c922e25b48_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("70ac8c63e43ab8d80284b9c922e25b48-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _753144_cats_icon {
            get {
                object obj = ResourceManager.GetObject("753144_cats_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9004798_arrow_direction_right_next_icon {
            get {
                object obj = ResourceManager.GetObject("9004798_arrow_direction_right_next_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9073941_heart_circle_icon {
            get {
                object obj = ResourceManager.GetObject("9073941_heart_circle_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9074017_paw_icon {
            get {
                object obj = ResourceManager.GetObject("9074017_paw_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chihuahua_de_color_blanco_y_tostado_4093fa98_22115144814_900x900 {
            get {
                object obj = ResourceManager.GetObject("chihuahua-de-color-blanco-y-tostado_4093fa98_22115144814_900x900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap como_es_el_gato_azul_ruso_22207_600 {
            get {
                object obj = ResourceManager.GetObject("como_es_el_gato_azul_ruso_22207_600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap como_es_el_temperamento_del_bichon_maltes_52616_600 {
            get {
                object obj = ResourceManager.GetObject("como_es_el_temperamento_del_bichon_maltes_52616_600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap como_saber_si_mi_husky_es_puro_50564_orig {
            get {
                object obj = ResourceManager.GetObject("como_saber_si_mi_husky_es_puro_50564_orig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dibujos_de_perritos_png_transparent_png_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("dibujos-de-perritos-png-transparent-png-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fotolia_82719975 {
            get {
                object obj = ResourceManager.GetObject("fotolia_82719975", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_birmano_5d9cb986_230412112714_1000x1500 {
            get {
                object obj = ResourceManager.GetObject("gato-birmano_5d9cb986_230412112714_1000x1500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_bombay_2ce041eb_230328173123_900x900 {
            get {
                object obj = ResourceManager.GetObject("gato-bombay_2ce041eb_230328173123_900x900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_bombay_953c56a7_230328173355_1000x667 {
            get {
                object obj = ResourceManager.GetObject("gato-bombay_953c56a7_230328173355_1000x667", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_britanico_de_pelo_corto {
            get {
                object obj = ResourceManager.GetObject("gato-britanico-de-pelo-corto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_siames {
            get {
                object obj = ResourceManager.GetObject("gato-siames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gato_sin_pelo_00000000_230405095919_900x900 {
            get {
                object obj = ResourceManager.GetObject("gato-sin-pelo_00000000_230405095919_900x900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gratis_png_marco_de_flores_amarillas_y_verdes_bordes_y_marcos_contenido_gratuito_palabras_de_compasion__2__removebg_preview {
            get {
                object obj = ResourceManager.GetObject("gratis-png-marco-de-flores-amarillas-y-verdes-bordes-y-marcos-contenido-gratuito-" +
                        "palabras-de-compasion__2_-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gratis_png_marco_de_flores_amarillas_y_verdes_bordes_y_marcos_contenido_gratuito_palabras_de_compasion_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("gratis-png-marco-de-flores-amarillas-y-verdes-bordes-y-marcos-contenido-gratuito-" +
                        "palabras-de-compasion-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_animal_shelter_related_to_volunteering_symbol_comic_style_help_and_support_friendship_vector_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("icon-animal-shelter-related-to-volunteering-symbol-comic-style-help-and-support-f" +
                        "riendship-vector-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icono_de_atencion_al_cliente_el_estilo_de_esquema_w6ghna_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("icono-de-atencion-al-cliente-el-estilo-de-esquema-w6ghna-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iStock_501597845_e1664121183957_1024x819 {
            get {
                object obj = ResourceManager.GetObject("iStock-501597845-e1664121183957-1024x819", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pet_adoption {
            get {
                object obj = ResourceManager.GetObject("pet adoption", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pet_adoption1 {
            get {
                object obj = ResourceManager.GetObject("pet adoption1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cute_cartoon_dog_puppy_sticker_png_image_9029372 {
            get {
                object obj = ResourceManager.GetObject("pngtree-cute-cartoon-dog-puppy-sticker-png-image_9029372", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_cute_cartoon_puppy_png_image_2610797_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("pngtree-cute-cartoon-puppy-png-image_2610797-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Raza_de_perro_pomerania_blog_de_pampermut {
            get {
                object obj = ResourceManager.GetObject("Raza-de-perro-pomerania-blog-de-pampermut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raza_pekines {
            get {
                object obj = ResourceManager.GetObject("raza-pekines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shemsu_Sotis_Perun {
            get {
                object obj = ResourceManager.GetObject("Shemsu_Sotis_Perun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sitesdefaultfilesstylessquare_medium_440x440public2022_09Parson20Russell20Terrier {
            get {
                object obj = ResourceManager.GetObject("sitesdefaultfilesstylessquare_medium_440x440public2022-09Parson20Russell20Terrier" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
